version: '3.8'

services:
  postgres:
    image: postgres:latest
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    env_file:
      - .env.postgres

  rabbitmq:
    image: "rabbitmq:3-management"
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    ports:
      - "5672:5672"
      - "15672:15672"
    env_file:
      - .env.rabbitmq

  redis:
    image: redis:latest
    ports:
      - "6379:6379"
    env_file:
      - .env.redis


volumes:
  postgres_data:
  keycloak_postgres_data:
  rabbitmq_data:
