export const CRYPTO_HASH_SERVICE = 'CRYPTO_HASH_SERVICE';

export const CRYPTO_JWT_SERVICE = 'CRYPTO_JWT_SERVICE';
export const JWT_SERVICE_CONFIG = 'JWT_SERVICE_CONFIG';

export const CRYPTO_JWE_SERVICE = 'CRYPTO_JWE_SERVICE';
export const JWE_SERVICE_CONFIG = 'JWE_SERVICE_CONFIG';
