export enum FileType {
  IMAGE = 'IMAGE',
  VIDEO = 'VIDEO',
}

export enum UploadStatus {
  QUEUED = 'QUEUED', // 0
  PROCESSING = 'PROCESSING', // 1
  ENCODING = 'ENCODING', // 2
  FINISHED = 'FINISHED', // 3
  RESOLUTION_FINISHED = 'RESOLUTION_FINISHED', // 4
  FAILED = 'FAILED', // 5
  PRESIGNED_UPLOAD_STARTED = 'PRESIGNED_UPLOAD_STARTED', // 6
  PRESIGNED_UPLOAD_FINISHED = 'PRESIGNED_UPLOAD_FINISHED', // 7
  PRESIGNED_UPLOAD_FAILED = 'PRESIGNED_UPLOAD_FAILED', // 8
  CAPTIONS_GENERATED = 'CAPTIONS_GENERATED', // 9
  TITLE_OR_DESCRIPTION_GENERATED = 'TITLE_OR_DESCRIPTION_GENERATED' // 10
}
